name: Ste's Apache BookKeeper CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up java 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build, test and determine control flow coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -P adequacy-controlflow clean test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=StefanoBelli_bookkeeper
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build, test and determine control flow coverage
      run: mvn -P adequacy-controlflow clean test

